chore: Verify semantic messages via Pull Request title, not commits
KaTeX/KaTeX pull request #2683
Opened 2020-12-13 18:29 UTC by edemaine

KaTeX always squash-merges PRs, so this seems like the preferred way to ensure that final commits support semantic-release.  I'm hoping it will make fixing nonsemantic PRs easier as well.

2020-12-18 17:15 UTC, kevinbarabash approved these changes
Let's give it a try.

2020-12-18 18:21 UTC, ylemkimon requested changes
AFAIK, `semantic-pull-requests` already does that. It automatically detects the final commit title:
- If there is a single commit, it checks for the commit message
- If there are multiple commits, it checks for the PR title

2020-12-18 20:38 UTC, edemaine commented
@ylemkimon Thanks for the explanation. I guess the issue then is that single-commit PRs don't look at the PR title, so we can't change the PR title to satisfy the check, making it annoying to merge single-commit PRs. Perhaps this change will make all PRs act like the multi-commit case?

2021-04-03 21:02 UTC, edemaine commented
Could we try merging this? [This comment](https://github.com/zeke/semantic-pull-requests/issues/112#issuecomment-709389100) suggests that it might work...  And it does seem that `titleOnly` is set to `false` by default.

2021-04-05 19:58 UTC, ylemkimon commented
However, in the case of a single commit, GitHub automatically fills the title of the merge commit with its title. So the red light means the merger should _manually_ change the commit title.

2021-04-06 13:04 UTC, edemaine commented
My goal was to be able to manually change the PR title (which is easy in the GitHub interface), rather than having to manually change the commit title (which requires checking out the branch and force-pushing).

2021-04-07 19:31 UTC, ylemkimon commented
Currently, `semantic-pull-requests` is not a required status check, so a pull request can be merged even if it fails. I think failed status would serve as a reminder to change the merge commit title via the GitHub interface.

2021-04-07 20:25 UTC, edemaine commented
Ah, I see, the intent is to edit the commit title in the "squash" interface.  That makes sense.

I somehow thought the check was required, but you're right that it isn't.  Should it be?

2021-04-08 19:13 UTC, ylemkimon commented
@edemaine Unfortunately, updating the PR title doesn't affect the title of merge commit if there is a single commit. Since a non-compliant commit message doesn't break KaTeX itself, I think making it not required is okay.

2021-10-30 07:32 UTC, closed without merging