feat: \nonumber and \notag support
KaTeX/KaTeX pull request #2952
Opened 2021-04-22 00:07 UTC by edemaine

Support `\nonumber` (and equivalent `\notag`) using a global macro `\@eqnsw` to track whether one occurs in each row, similar to how amsmath uses global `\@eqnswtrue`/`\@eqnswfalse`.

Fix #2950

I added basic documentation (also for `align*` which was missing), but still need to add tests.

2021-04-22 15:08 UTC, edemaine commented
Hmm, perhaps I should try to implement `\tag`-per-row at the same time; this should be doable with a similar (if not the same) mechanism.

2021-04-25 14:55 UTC, edemaine commented
OK, I've added support for `\tag` in rows. This was harder than expected, but not too bad. See root post for details. Now ready for review.

2021-09-05 15:26 UTC, edemaine commented
I fixed the merge conflicts here, so this is ready to review again. FWIW, we've had a recent explicit request for this feature (#3183), and #2379 has 5 thumbs-up. PR #3214 also currently depends on this one. Let me know if you'd rather I split this up into multiple PRs.

2021-10-31 03:31 UTC, ylemkimon requested changes
LGTM. Sorry for the delayed review. I think `subparse` logic can be improved later.

2021-10-31 03:31 UTC, ylemkimon commented on src/environments/array.js
> +              false : undefined,
```suggestion
            autoTag: getAutoTag(context.envName),
```

2021-10-31 03:31 UTC, ylemkimon commented on src/environments/array.js
> +                     context.envName === "gather*" ? false : undefined,
```suggestion
            autoTag: getAutoTag(context.envName),
```

2021-10-31 03:31 UTC, ylemkimon commented on src/environments/array.js
> +            autoTag: context.envName === "equation",
```suggestion
            autoTag: getAutoTag(context.envName),
```

2021-10-31 03:31 UTC, ylemkimon commented on src/environments/array.js
```suggestion

const getAutoTag = name => name.indexOf("ed") === -1 ? name.indexOf("*") === -1
    : undefined;
```
(below `validateAmsEnvironmentContext`)

2021-10-31 03:31 UTC, ylemkimon commented on src/Parser.js
> +        this.gullet.feedTokens(tokens);
```suggestion
        this.gullet.pushToken(new Token("}"));
        this.gullet.pushTokens(tokens);
```

2021-10-31 03:31 UTC, ylemkimon commented on src/MacroExpander.js
> +
```suggestion
```

2021-10-31 18:09 UTC, edemaine commented
@ylemkimon Thanks for the nice improvements! Should be ready to look at again.

2021-10-31 21:39 UTC, ylemkimon approved these changes

2021-10-31 21:40 UTC, merged