feat: add \emph
KaTeX/KaTeX pull request #3963
Opened 2024-06-30 17:51 UTC by grigoriy-reshetniak

**What is the previous behavior before this PR?**
`\emph` wasn't supported

**What is the new behavior after this PR?**
`\emph` is supported

![image](https://github.com/KaTeX/KaTeX/assets/8845364/1e1697ea-fcf3-4e7c-bf53-d977af0db170)

Implements default behavior of making text italic if it's not and making text upright if it's italic. Please let me know ff more complex rules are required.

Closes #3566

2024-07-01 16:17 UTC, edemaine requested changes
I didn't realize that `\emph` works in math mode.  Your implementation seems to exactly match LaTeX behavior:

```latex
x+\emph{foo \emph{bar}}+\textit{foo \emph{bar}}
```

![image](https://github.com/KaTeX/KaTeX/assets/2218736/2f023015-5c82-4337-aff1-fae98420f4a4)

LaTeX:
![image](https://github.com/KaTeX/KaTeX/assets/2218736/a9d6ca1f-03b2-481b-b294-4613bfc5b21a)

In addition to the implementation comments below, can you add some tests? Something like ``expect`\emph{foo \emph{bar}}`.toParseLike`\textit{foo \textup{bar}}` ``.

2024-07-01 16:17 UTC, edemaine commented on src/functions/text.js
> +    "\\emph": "textit",
I think it would be better to avoid including this as a shape (see below).

2024-07-01 16:17 UTC, edemaine commented on src/functions/text.js
> +    } else if (options.fontShape === "textit" && font === "\\emph") {
I'd suggest changing this to `if (font === "\emph")` and using `options.withTextFontShape` (enforcing text mode) with `"textit"` or `"textup"` according to `options.fontShape`.

2024-07-01 18:28 UTC, grigoriy-reshetniak commented
My bad, I should've added test from the beginning

2024-07-02 15:35 UTC, edemaine approved these changes
Looks good! I re-organized the Fonts docs table to include `\emph`. Could you double check it looks good before I merge?

2024-07-02 15:47 UTC, grigoriy-reshetniak reviewed
Looks good to me.

2024-07-02 15:49 UTC, merged